# Generated by Django 5.2 on 2025-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdb",
            name="humidty",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="weatherdb",
            name="pressure",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
