# Generated by Django 5.2 on 2025-05-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weatherApp", "0002_weatherdb_humidty_weatherdb_pressure"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherdb",
            old_name="humidty",
            new_name="humidity",
        ),
    ]
